### PR TITLE
Rebase against latest upstream Crucible

### PR DESCRIPTION
**Pull request by abays**
This will set our Crucible fork to the `380937382a9929bc3af76724e4a9186cf1d61f50` upstream commit

### CODE REVIEW

**Comment by stuggi** [comment]
wondering if we need this fork, or if we could just pin to an upstream commit? do we have customization for our needs on top of the clone?

**Comment by abays** [comment]
> wondering if we need this fork, or if we could just pin to an upstream commit? do we have customization for our needs on top of the clone?

As of https://github.com/openstack-k8s-operators/osp-director-dev-tools/pull/425, we no longer have any customizations that we need (other than the ones we inject in the course of our dev-tools logic via `replace` modules).  So we could just pin to Crucible itself at a particular commit.  If we needed customizations in the future, we could point back to this fork again.

**Comment by stuggi** [comment]
> > wondering if we need this fork, or if we could just pin to an upstream commit? do we have customization for our needs on top of the clone?
> 
> As of [openstack-k8s-operators/osp-director-dev-tools#425](https://github.com/openstack-k8s-operators/osp-director-dev-tools/pull/425), we no longer have any customizations that we need (other than the ones we inject in the course of our dev-tools logic via `replace` modules). So we could just pin to Crucible itself at a particular commit. If we needed customizations in the future, we could point back to this fork again.

sounds good. I'd vote for that, or what you think @olliewalsh @dprince ?

**Comment by abays** [comment]
> > > wondering if we need this fork, or if we could just pin to an upstream commit? do we have customization for our needs on top of the clone?
> > 
> > 
> > As of [openstack-k8s-operators/osp-director-dev-tools#425](https://github.com/openstack-k8s-operators/osp-director-dev-tools/pull/425), we no longer have any customizations that we need (other than the ones we inject in the course of our dev-tools logic via `replace` modules). So we could just pin to Crucible itself at a particular commit. If we needed customizations in the future, we could point back to this fork again.
> 
> sounds good. I'd vote for that, or what you think @olliewalsh @dprince ?

I tried using the Crucible repo directly today with dev-tools and the deployment went just fine, so I'll make that change to the other PR if @olliewalsh and @dprince agree.

**Comment by dprince** [comment]
I am good with pinning to a specific release of Crucible.

**Pull request closed without merging**
